### ISSUE TITLE
Feature request: exempt certain categories from blocklist

### ISSUE THREAD

**Issue by Unspec7** [flmorg/cleanuperr#13]
Would it be possibly to implement a category exemption for blocklisting? I use the qbittorrent client I host as a general torrenting instance, and don't want to use more VPN slots than necessary by spinning up another qbittorrent instance behind gluetun. As such, it would be really nice if this program could exempt certain categories (e.g. prowlarr, software, etc) from the blocklist application, so that I can still download software and the such by using those categories, yet block them if they're being downloaded for radarr/sonarr/lidarr/etc.

Thanks!

**Comment by Flaminel** [comment]
The blocklist only applies for the items present in Sonarr/Radarr's queue. You're right that it may not be clear enough from the instructions, so I'll need to update them to state that.

So the blocklist functionality does not look at all items in your download client, but only those that are present in the *arr queue.

**Comment by Unspec7** [comment]
Nice! Thanks
