### ISSUE TITLE
Radarr Trying to cleanup on port 8080 even though running on port 443?

### ISSUE THREAD

**Issue by retepz** [flmorg/cleanuperr#28]
See the below screenshot.  Cleanuperr can find a stuck radarr download but when it tries to remove it, it throws an exception.  Whats confusing to me is its trying to reach localhost:8080 when nothing is on that?  My radarr and sonarr are running on port 443 using my own domain (blacked out in the screenshot for privacy reasons)

![image](https://github.com/user-attachments/assets/9bfab467-4dff-44eb-a918-f7d694cd1726)

After looking at the environment variables (below), is that a red herring and just referring to the port the app is running on?
![image](https://github.com/user-attachments/assets/d24564c7-f233-4b52-9703-532318c39b65)

**Comment by Flaminel** [comment]
Yeah, that 8080 port is from the framework so it's not related. Am I correct to say that you haven't actually configured a download client in cleanuperr? The error is probably because it's trying to access the download client (localhost:8080 is used by default) and so it fails. It's not necessarily a bug, but it is on my to-do list to make cleanuperr function without a download client as well.

**Comment by oldretepzold** [comment]
> Yeah, that 8080 port is from the framework so it's not related. Am I correct to say that you haven't actually configured a download client in cleanuperr? The error is probably because it's trying to access the download client (localhost:8080 is used by default) and so it fails. It's not necessarily a bug, but it is on my to-do list to make cleanuperr function without a download client as well.

No, I set download client to transmission....

**Comment by Flaminel** [comment]
You're right. It was hard to see as the env vars are not sorted, my bad. Could you provide your setup (docker compose for cleanuperr or whatever), excluding sensitive data?

**Comment by oldretepzold** [comment]
I used the unraid "docker app".  Something was wonky with it i guess because switching to docker compose (on a non unraid machine) works.  /shrug

**Comment by Flaminel** [comment]
The Unraid community app is not yet up to date, as it was not maintained by me. A new community app is on the way though, which I'll be keeping updated.

**Comment by oldretepzold** [comment]
> The Unraid community app is not yet up to date, as it was not maintained by me. A new community app is on the way though, which I'll be keeping updated.

Its supposed to be using the most up to date docker image and I changed out the environment variables that changed/removed.  Weird.
